blank_issues_enabled: true
contact_links:
  - name: Ask a question or recieve help
    url: https://github.com/deutschemodelunitednations/munify-chase/discussions/categories/support
    about: Please use the help tab of the discussion section to recieve help and ask questions.
